### ISSUE TITLE
Error To Read SQS queue

### ISSUE THREAD

**Issue by ze-engineering-code-challenge** [qubole/s3-sqs-connector#5] opened 2020-07-23 17:59 UTC
Hi, how are you?

Thank you for provinding the lib, will help a lot.

I'm facing some errors when a try to create my spark structured streaming pipeline

20/07/23 17:57:13 ERROR MicroBatchExecution: Query [id = c9b4658e-af4b-41ab-939f-22149636e025, runId = 7aede0d8-a016-48fd-8ad9-41ba08539f2d] terminated with error
java.lang.NoSuchMethodError: org.apache.spark.sql.Dataset$.ofRows$default$3()Ljava/lang/String;
	at org.apache.spark.sql.streaming.sqs.SqsSource.getBatch(SqsSource.scala:80)
	at org.apache.spark.sql.execution.streaming.MicroBatchExecution$$anonfun$org$apache$spark$sql$execution$streaming$MicroBatchExecution$$runBatch$3$$anonfun$apply$10.apply(MicroBatchExecution.scala:438)
	at org.apache.spark.sql.execution.streaming.MicroBatchExecution$$anonfun$org$apache$spark$sql$execution$streaming$MicroBatchExecution$$runBatch$3$$anonfun$apply$10.apply(MicroBatchExecution.scala:434)
	at scala.collection.TraversableLike$$anonfun$flatMap$1.apply(TraversableLike.scala:241)
	at scala.collection.TraversableLike$$anonfun$flatMap$1.apply(TraversableLike.scala:241)
	at scala.collection.Iterator$class.foreach(Iterator.scala:891)
	at scala.collection.AbstractIterator.foreach(Iterator.scala:1334)
	at scala.collection.IterableLike$class.foreach(IterableLike.scala:72)
	at org.apache.spark.sql.execution.streaming.StreamProgress.foreach(StreamProgress.scala:25)
	at scala.collection.TraversableLike$class.flatMap(TraversableLike.scala:241)
	at org.apache.spark.sql.execution.streaming.StreamProgress.flatMap(StreamProgress.scala:25)
	at org.apache.spark.sql.execution.streaming.MicroBatchExecution$$anonfun$org$apache$spark$sql$execution$streaming$MicroBatchExecution$$runBatch$3.apply(MicroBatchExecution.scala:434)
	at org.apache.spark.sql.execution.streaming.MicroBatchExecution$$anonfun$org$apache$spark$sql$execution$streaming$MicroBatchExecution$$runBatch$3.apply(MicroBatchExecution.scala:434)
	at org.apache.spark.sql.execution.streaming.ProgressReporter$class.reportTimeTaken(ProgressReporter.scala:351)
	at org.apache.spark.sql.execution.streaming.StreamExecution.reportTimeTaken(StreamExecution.scala:58)
	at org.apache.spark.sql.execution.streaming.MicroBatchExecution.org$apache$spark$sql$execution$streaming$MicroBatchExecution$$runBatch(MicroBatchExecution.scala:433)
	at org.apache.spark.sql.execution.streaming.MicroBatchExecution$$anonfun$runActivatedStream$1$$anonfun$apply$mcZ$sp$1.apply$mcV$sp(MicroBatchExecution.scala:198)
	at org.apache.spark.sql.execution.streaming.MicroBatchExecution$$anonfun$runActivatedStream$1$$anonfun$apply$mcZ$sp$1.apply(MicroBatchExecution.scala:166)
	at org.apache.spark.sql.execution.streaming.MicroBatchExecution$$anonfun$runActivatedStream$1$$anonfun$apply$mcZ$sp$1.apply(MicroBatchExecution.scala:166)
	at org.apache.spark.sql.execution.streaming.ProgressReporter$class.reportTimeTaken(ProgressReporter.scala:351)
	at org.apache.spark.sql.execution.streaming.StreamExecution.reportTimeTaken(StreamExecution.scala:58)
	at org.apache.spark.sql.execution.streaming.MicroBatchExecution$$anonfun$runActivatedStream$1.apply$mcZ$sp(MicroBatchExecution.scala:166)
	at org.apache.spark.sql.execution.streaming.ProcessingTimeExecutor.execute(TriggerExecutor.scala:56)
	at org.apache.spark.sql.execution.streaming.MicroBatchExecution.runActivatedStream(MicroBatchExecution.scala:160)
	at org.apache.spark.sql.execution.streaming.StreamExecution.org$apache$spark$sql$execution$streaming$StreamExecution$$runStream(StreamExecution.scala:281)
	at org.apache.spark.sql.execution.streaming.StreamExecution$$anon$1.run(StreamExecution.scala:193)
Exception in thread "stream execution thread for [id = c9b4658e-af4b-41ab-939f-22149636e025, runId = 7aede0d8-a016-48fd-8ad9-41ba08539f2d]" java.lang.NoSuchMethodError: org.apache.spark.sql.Dataset$.ofRows$default$3()Ljava/lang/String;
	at org.apache.spark.sql.streaming.sqs.SqsSource.getBatch(SqsSource.scala:80)
	at org.apache.spark.sql.execution.streaming.MicroBatchExecution$$anonfun$org$apache$spark$sql$execution$streaming$MicroBatchExecution$$runBatch$3$$anonfun$apply$10.apply(MicroBatchExecution.scala:438)
	at org.apache.spark.sql.execution.streaming.MicroBatchExecution$$anonfun$org$apache$spark$sql$execution$streaming$MicroBatchExecution$$runBatch$3$$anonfun$apply$10.apply(MicroBatchExecution.scala:434)
	at scala.collection.TraversableLike$$anonfun$flatMap$1.apply(TraversableLike.scala:241)
	at scala.collection.TraversableLike$$anonfun$flatMap$1.apply(TraversableLike.scala:241)
	at scala.collection.Iterator$class.foreach(Iterator.scala:891)
	at scala.collection.AbstractIterator.foreach(Iterator.scala:1334)
	at scala.collection.IterableLike$class.foreach(IterableLike.scala:72)
	at org.apache.spark.sql.execution.streaming.StreamProgress.foreach(StreamProgress.scala:25)
	at scala.collection.TraversableLike$class.flatMap(TraversableLike.scala:241)
	at org.apache.spark.sql.execution.streaming.StreamProgress.flatMap(StreamProgress.scala:25)
	at org.apache.spark.sql.execution.streaming.MicroBatchExecution$$anonfun$org$apache$spark$sql$execution$streaming$MicroBatchExecution$$runBatch$3.apply(MicroBatchExecution.scala:434)
	at org.apache.spark.sql.execution.streaming.MicroBatchExecution$$anonfun$org$apache$spark$sql$execution$streaming$MicroBatchExecution$$runBatch$3.apply(MicroBatchExecution.scala:434)
	at org.apache.spark.sql.execution.streaming.ProgressReporter$class.reportTimeTaken(ProgressReporter.scala:351)
	at org.apache.spark.sql.execution.streaming.StreamExecution.reportTimeTaken(StreamExecution.scala:58)
	at org.apache.spark.sql.execution.streaming.MicroBatchExecution.org$apache$spark$sql$execution$streaming$MicroBatchExecution$$runBatch(MicroBatchExecution.scala:433)
	at org.apache.spark.sql.execution.streaming.MicroBatchExecution$$anonfun$runActivatedStream$1$$anonfun$apply$mcZ$sp$1.apply$mcV$sp(MicroBatchExecution.scala:198)
	at org.apache.spark.sql.execution.streaming.MicroBatchExecution$$anonfun$runActivatedStream$1$$anonfun$apply$mcZ$sp$1.apply(MicroBatchExecution.scala:166)
	at org.apache.spark.sql.execution.streaming.MicroBatchExecution$$anonfun$runActivatedStream$1$$anonfun$apply$mcZ$sp$1.apply(MicroBatchExecution.scala:166)
	at org.apache.spark.sql.execution.streaming.ProgressReporter$class.reportTimeTaken(ProgressReporter.scala:351)
	at org.apache.spark.sql.execution.streaming.StreamExecution.reportTimeTaken(StreamExecution.scala:58)
	at org.apache.spark.sql.execution.streaming.MicroBatchExecution$$anonfun$runActivatedStream$1.apply$mcZ$sp(MicroBatchExecution.scala:166)
	at org.apache.spark.sql.execution.streaming.ProcessingTimeExecutor.execute(TriggerExecutor.scala:56)
	at org.apache.spark.sql.execution.streaming.MicroBatchExecution.runActivatedStream(MicroBatchExecution.scala:160)
	at org.apache.spark.sql.execution.streaming.StreamExecution.org$apache$spark$sql$execution$streaming$StreamExecution$$runStream(StreamExecution.scala:281)
	at org.apache.spark.sql.execution.streaming.StreamExecution$$anon$1.run(StreamExecution.scala:193)
Traceback (most recent call last):
  File "/usr/lib/spark/python/lib/pyspark.zip/pyspark/sql/utils.py", line 63, in deco
  File "/usr/lib/spark/python/lib/py4j-0.10.7-src.zip/py4j/protocol.py", line 328, in get_return_value
py4j.protocol.Py4JJavaError: An error occurred while calling o83.awaitTermination.
: org.apache.spark.sql.streaming.StreamingQueryException: org.apache.spark.sql.Dataset$.ofRows$default$3()Ljava/lang/String;
=== Streaming Query ===
Identifier: [id = c9b4658e-af4b-41ab-939f-22149636e025, runId = 7aede0d8-a016-48fd-8ad9-41ba08539f2d]
Current Committed Offsets: {}
Current Available Offsets: {SqsSource[https://sqs.us-west-2.amazonaws.com/713440373855/emr-sqs-test]: {"logOffset":0}}

My readstream

df_stream = spark.readStream\
     .format("s3-sqs")\
     .schema(stockout_raw_schema)\
     .option("sqsUrl", 'https://sqs.us-west-2.amazonaws.com/713440373855/emr-sqs-test')\
     .option("region", 'us-west-2')\
     .option("fileFormat", "parquet")\
     .option("sqsFetchIntervalSeconds", "2")\
     .option("useInstanceProfileCredentials", "true")\
     .option("sqsLongPollingWaitTimeSeconds", "5")\
     .load()

my sink

def write_parquet_stream(spark_data_frame, checkpoint_location_folder, write_folder_path):

    df_write_query = spark_data_frame \
                      .writeStream \
                      .outputMode('append') \
                      .format('parquet')\
                      .option("checkpointLocation", checkpoint_location_folder) \
                      .start(write_folder_path)

    df_write_query.awaitTermination()

could you help me?

Thank you so much.

**Comment by abhishekd0907** [comment] 2020-07-23 18:11
@ze-engineering-code-challenge 

Are you facing this issue on EMR? A user had reported this issue with EMR earlier but he was able to fix it eventually.
Refer to the comment below:
https://github.com/qubole/s3-sqs-connector/issues/1#issuecomment-615100126

**Comment by abhishekd0907** [comment] 2020-07-23 18:16
@ze-engineering-code-challenge 

Which spark version are you using?

`Dataset.ofRows` seems to be a valid method in open source spark 2.4.0 [Check here](https://github.com/apache/spark/blob/0a4c03f7d084f1d2aa48673b99f3b9496893ce8d/sql/core/src/main/scala/org/apache/spark/sql/Dataset.scala#L77)

I'll try to reproduce the issue with open source spark and see.

**Comment by rubenssoto** [comment] 2020-07-23 18:21
Hi, thank you for awnser, ze-engineering-code-challenge its me

Yeah Im using EMR 5.30.1 with spark 2.4.5. I read the post that you send to me, but Im not using Jupiter to run the script Im using spark-submit 

spark-submit --packages com.qubole:spark-sql-streaming-sqs_2.11:0.5.1 script.py

**Comment by abhishekd0907** [comment] 2020-07-23 18:38
@rubenssoto 

is it possible for you to confirm from EMR support if they have removed/changed this method [Dataset.ofRows](https://github.com/apache/spark/blob/cee4ecbb16917fa85f02c635925e2687400aa56b/sql/core/src/main/scala/org/apache/spark/sql/Dataset.scala#L76) as compared to its open-source version.

I might be able to change the implementation in my code if that's the case.

**Comment by rubenssoto** [comment] 2020-07-23 19:10
I've opened a ticket :)

Do you have plans to support spark 3.0?

**Comment by abhishekd0907** [comment] 2020-07-24 06:41
Sure let me know once you hear back from them. 

DataSourceV1 sources still work on Spark-3 should this code work with Spark-3. But you might get this `Dataset.ofRows` issue on EMR Spark-3 as well so let's resolve this first.

Migrating to DataSourceV2 is on the roadmap but timeline is not fixed right now.

**Comment by rubenssoto** [comment] 2020-07-24 15:07
Sure, Im waiting aws response yet.

**Comment by abhishekd0907** [comment] 2020-11-09 19:26
Duplicate of Issue #1 

Refer:
https://github.com/qubole/s3-sqs-connector/issues/1#issuecomment-680006166

**Comment by abhishekd0907** [comment] 2020-11-09 19:27
Refer:
https://github.com/qubole/s3-sqs-connector/issues/1#issuecomment-680006166

**Closed as completed by abhishekd0907** 2020-11-09 19:26 UTC
